version: '3'

services:
  web:
    build:
      context: .
    environment:
      - OPENAI_API_KEY
      - SERPAPI_API_KEY
      - LANGCHAIN_TRACING_V2
      - LANGCHAIN_ENDPOINT
      - LANGCHAIN_API_KEY
      - LANGCHAIN_PROJECT
    ports:
      - 8000:8000
