name: Test

on:
  push:
    branches:
      - main
      - "*"
  schedule:
    - cron: "58 11 * * *"
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build:
    env:
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_PROJECT: wai-ga

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run pytest
        run: |
          poetry run pytest -rP
