name: Test

on:
  push:
    branches:
      - main
      - '*'
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run pytest
      run: |
        poetry run pytest -rP
